GET  https://dietappreact.herokuapp.com/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDgyODYxNTEsImV4cCI6MTYwODI4NjE2NiwiYXVkIjoiNWZkYzdmYzZkNjczNzUwMDE3MmFlZGJjIiwiaXNzIjoiaHR0cDovL2RpZXRhbm90ZS5uZXRsaWZ5LmFwcC8ifQ.IVDbpE_In0M1A-1EoBu4mz1Da8Ej5XzPPtzRG16o4Nw
###Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "password11"
}


###Register
POST http://localhost:8080/auth/register
Content-Type:application/json

{
    "email": "test@gmail.com",
    "password": "password11"
}

###Refresh token
POST https://dietappreact.herokuapp.com/auth/refresh-token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDgyODYxNTEsImV4cCI6MTYzOTg0Mzc1MSwiYXVkIjoiNWZkYzdmYzZkNjczNzUwMDE3MmFlZGJjIiwiaXNzIjoiaHR0cDovL2RpZXRhbm90ZS5uZXRsaWZ5LmFwcC8ifQ.kxPzWeSTFLMAhqj7zPmSuvac3v7lY4wV2GsiJ2bGzs4"
}
###Logout
DELETE https://dietappreact.herokuapp.com/auth/logout
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDc5ODc5NTksImV4cCI6MTYzOTU0NTU1OSwiYXVkIjoiNWZkNTUxZjk4MWY1ZWYzZmZjMGM0M2YxIiwiaXNzIjoiaHR0cDovL2RpZXRhbm90ZS5uZXRsaWZ5LmFwcC8ifQ.8WsUoIhPS_Ij7tb-bj0Au0SyfgtiZGYvkLNN4oN9jPM"
}