GET  https://dietappreact.herokuapp.com/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXNzYWdlIjoib2siLCJpYXQiOjE2MDkxNTgxNjksImV4cCI6MTYwOTE1ODc2OSwiYXVkIjoiNWZlOWNlMTIwZGQwMzUzYWE0YjQ5MjNkIiwiaXNzIjoiaHR0cDovL2RpZXRhbm90ZS5uZXRsaWZ5LmFwcC8ifQ.5gx4z7tfE74LSQ5ILCqpr9s4TCf9CXCaLv2g3cH7oJU

###Login OKa
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "cookie1@1.com",
    "password": "password11"
}


###Register OK
POST http://localhost:8080/auth/register
Content-Type:application/json

{
    "email": "fix@1.com",
    "password": "password11"
    
}

###Refresh token
POST http://localhost:8080/auth/refresh-token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDk1OTk0NDAsImV4cCI6MTYxMDIwNDI0MCwiYXVkIjoiNWZmMDM3NjFhNGE1N2UyYjQ4MTI5ZTAzIiwiaXNzIjoiaHR0cDovL2RpZXRhbm90ZS5uZXRsaWZ5LmFwcC8ifQ.bjlSaZusSnZtB7gN6wnEshxqV3szBSqqc8fBMfMnG9E",
"userId": "5fe9c9688bd7c24ef043a2cd"

}


###Logout  OK front->remove accesToken
DELETE http://localhost:8080/auth/logout
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDk2MDA0MjEsImV4cCI6MTYxMDIwNTIyMSwiYXVkIjoiNWZmMDM3NjFhNGE1N2UyYjQ4MTI5ZTAzIiwiaXNzIjoiaHR0cDovL2RpZXRhbm90ZS5uZXRsaWZ5LmFwcC8ifQ.s92s9HkoepzyYI3jirYTsS3oKw18__PRtEZt-COd_T8; Max-Age=604800; Path=/; Expires=Sat, 09 Jan 2021 15:13:41 GMT,accesToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXNzYWdlIjoib2siLCJpYXQiOjE2MDk2MDA0MjEsImV4cCI6MTYwOTYwMTAyMSwiYXVkIjoiNWZmMDM3NjFhNGE1N2UyYjQ4MTI5ZTAzIiwiaXNzIjoiaHR0cDovL2RpZXRhbm90ZS5uZXRsaWZ5LmFwcC8ifQ.DffhzpzkK07ucIU1Ec7tTVjcm2jKrNundSVynEFV4cs; Max-Age=600; Path=/; Expires=Sat, 02 Jan 2021 15:23:41 GMT,userId=5ff03761a4a57e2b48129e03; Max-Age=604800; Path=/; Expires=Sat, 09 Jan 2021 15:13:41 GMT

{
}


###nested refresh tokens
POST http://localhost:8080/auth/newR
Content-Type: application/json

{
    "email": "test221@example.com",
    "password": "123",
    "refreshToken": "2121"
}